echo "********************************************************************"
echo "* Vitejte v AI ARCH ISO (Auto-Install)                           *"
echo "* *"
echo "* Hostname: chdai                                                *"
echo "* Automaticka instalace by mela bezet...                         *"
echo "********************************************************************"
